apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-boot-app
  labels:
    app: sprint-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sprint-boot-app
  template:
    metadata:
      labels:
        app: sprint-boot-app
    spec:
      containers:
      - name: sprint-boot-app
        image: ultimate-cicd:7
        ports:
        - containerPort: 8080
